dev:
	@go run *.go

port:
	@heroku config:set PORT=1234

symbol:
	@heroku config:set SYMBOL=BTC

price:
	@heroku config:set BASE_PRICE=33000

bot_token:
	@heroku config:set TELE_BOT_TOKEN=abc

bot_id:
	@heroku config:set TELE_BOT_ID=abc

deploy:
	@git push heroku master 