dev:
	@go run *.go

port:
	@heroku config:set PORT=1234

symbol:
	@heroku config:set SYMBOL=BTC

price:
	@heroku config:set BASE_PRICE=33000

bot_token:
	@heroku config:set TELE_BOT_TOKEN=abc

bot_id:
	@heroku config:set TELE_BOT_ID=abc

deploy:
	@git push heroku master

mentions:
	@heroku config:set MENTIONS=@abc

heroku_url:
	@heroku config:set HEROKU_URL=https://herokuapp.com/ping

coin_all_in:
	@heroku config:set SYMBOL=BTC BASE_PRICE=37000.143 PROFIT_PERCENTAGE=110 LOSS_ALERT=false PROFIT_ALERT=true EXCHANE_PLATFOM=binance